### ISSUE TITLE
Don't use server to stream data

### ISSUE THREAD

**Issue by xabufr** [r0mdau/stream-it#1]
see http://peerjs.com/, for example.

Pro:
- Don't need good brandwidth for server
- Performance
  Cons:
- A little more difficult to use ?
- Maybe NAT router can be problematic

**Comment by r0mdau** [comment]
@xabufr In big organizations it's impossible to use a direct stream between browsers without using a central access because of routing.

New release for big files, the recevier browser download the file from a link provided by the server ;)
https://github.com/r0mdau/stream-it/tree/develop
